---
- name: Webhook to Automation Orchestrator Demo
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Forward event to Orchestrator
      condition: event is defined
      actions:
        - run_job_template:
            name: Orchestrator Webhook Forward
            organization: Default
            job_args:
              extra_vars:
                orchestrator_event: "{{ event }}"
                orchestrator_topic: eda-webhook
