---
- name: Event Stream to Automation Orchestrator Demo
  hosts: all
  sources:
    - ansible.eda.generic:
        source_name: demo-event-stream

  rules:
    - name: Forward event to Orchestrator
      condition: event.meta is defined
      actions:
        - run_job_template:
            name: Orchestrator Webhook Forward
            organization: Default
            job_args:
              extra_vars:
                orchestrator_event: "{{ event }}"
                orchestrator_topic: eda-webhook
